apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment-tah
  namespace: tah
  labels:
    app: ollama-tah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-tah
  template:
    metadata:
      labels:
        app: ollama-tah
    spec:
      containers:
      - name: ollama-tah
        image: ollama/ollama:0.1.45-rc2
        ports:
        - containerPort: 11434
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service-tah
  namespace: tah
spec:
  selector:
    app: ollama-tah
  ports: 
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: ClusterIP